# Generated by Django 3.2.3 on 2021-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brampton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('province', models.CharField(max_length=1000)),
                ('mapaddress', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=1000)),
                ('vaccine1', models.CharField(max_length=1000)),
                ('vaccine2', models.CharField(max_length=1000)),
                ('appointment_details', models.CharField(max_length=1000)),
                ('hours1', models.CharField(max_length=1000)),
                ('hours2', models.CharField(max_length=1000)),
                ('hours3', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hamilton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('province', models.CharField(max_length=1000)),
                ('mapaddress', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=1000)),
                ('vaccine1', models.CharField(max_length=1000)),
                ('vaccine2', models.CharField(max_length=1000)),
                ('appointment_details', models.CharField(max_length=1000)),
                ('hours1', models.CharField(max_length=1000)),
                ('hours2', models.CharField(max_length=1000)),
                ('hours3', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=16)),
                ('location', models.CharField(choices=[('Toronto', 'Toronto'), ('Hamilton', 'Hamilton'), ('Mississauga', 'Mississauga'), ('Brampton', 'Brampton'), ('Ottawa', 'Ottawa')], default='Toronto', max_length=16)),
                ('street', models.CharField(max_length=64)),
                ('postalcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Mississauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('province', models.CharField(max_length=1000)),
                ('mapaddress', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=1000)),
                ('vaccine1', models.CharField(max_length=1000)),
                ('vaccine2', models.CharField(max_length=1000)),
                ('appointment_details', models.CharField(max_length=1000)),
                ('hours1', models.CharField(max_length=1000)),
                ('hours2', models.CharField(max_length=1000)),
                ('hours3', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ottawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('province', models.CharField(max_length=1000)),
                ('mapaddress', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=1000)),
                ('vaccine1', models.CharField(max_length=1000)),
                ('vaccine2', models.CharField(max_length=1000)),
                ('appointment_details', models.CharField(max_length=1000)),
                ('hours1', models.CharField(max_length=1000)),
                ('hours2', models.CharField(max_length=1000)),
                ('hours3', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Toronto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('province', models.CharField(max_length=1000)),
                ('mapaddress', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=1000)),
                ('vaccine1', models.CharField(max_length=1000)),
                ('vaccine2', models.CharField(max_length=1000)),
                ('appointment_details', models.CharField(max_length=1000)),
                ('hours1', models.CharField(max_length=1000)),
                ('hours2', models.CharField(max_length=1000)),
                ('hours3', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
    ]
