# Generated by Django 3.2.3 on 2021-05-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210515_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brampton',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='appointment_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='hours1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='hours2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='hours3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='mapaddress',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='pharmacy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='phone',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='province',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='vaccine1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='vaccine2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brampton',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='appointment_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='hours1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='hours2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='hours3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='phone',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='vaccine1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='hamilton',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='appointment_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='hours1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='hours2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='hours3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='mapaddress',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='pharmacy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='phone',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='province',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='vaccine1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='vaccine2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mississauga',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='appointment_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='hours1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='hours2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='hours3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='mapaddress',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='pharmacy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='phone',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='province',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='vaccine1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='vaccine2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ottawa',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
