# Generated by Django 3.2.3 on 2021-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_hamilton_vaccine2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AddField(
            model_name='information',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
        migrations.AddField(
            model_name='information',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
    ]
