# Generated by Django 3.2.3 on 2021-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210517_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='toronto',
            name='latitude',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='toronto',
            name='longitude',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
